# Use postgres/example user/password credentials
version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "example"
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: "redis:6.0.8"
    ports:
      - "6379:6379"

volumes:
  postgres-data-volume:
